#!/usr/bin/env bash
set -euo pipefail

echo "Render Secrets and Connection Values for Nexus HyperIntelligence"
echo ""
echo "1) Render API key (for CI + scripts)"
echo "   Navigation: Render Dashboard -> Account Settings -> API Keys -> Create API Key"
echo "   Save as: RENDER_API_KEY"
echo ""
echo "2) Service IDs required by GitHub Actions"
echo "   Navigation: Render Dashboard -> nexus-api -> Settings -> Service ID"
echo "   Save as: RENDER_NEXUS_API_SERVICE_ID"
echo ""
echo "3) Optional Blueprint ID (if using blueprint deploy mode)"
echo "   Navigation: Render Dashboard -> Blueprints -> nexus-hyperintelligence -> Blueprint ID"
echo "   Save as: RENDER_BLUEPRINT_ID"
echo ""
echo "4) API secrets"
echo "   Navigation: Render Dashboard -> nexus-api -> Environment"
echo "   Add: NEXUS_API_KEY"
echo "   Add: JWT_SECRET"
echo ""
echo "5) Neo4j credentials"
echo "   Navigation: Render Dashboard -> nexus-neo4j -> Environment"
echo "   Add: NEO4J_AUTH (format: neo4j/<strong-password>)"
echo "   Then in nexus-api environment set:"
echo "     NEO4J_USERNAME=neo4j"
echo "     NEO4J_PASSWORD=<strong-password>"
echo ""
echo "6) MinIO credentials"
echo "   Navigation: Render Dashboard -> nexus-minio -> Environment"
echo "   Add: MINIO_ROOT_USER"
echo "   Add: MINIO_ROOT_PASSWORD"
echo "   Then in nexus-api environment set:"
echo "     MINIO_ACCESS_KEY=<same as MINIO_ROOT_USER>"
echo "     MINIO_SECRET_KEY=<same as MINIO_ROOT_PASSWORD>"
echo ""
echo "7) Managed Postgres and Redis connection strings"
echo "   Postgres: Render Dashboard -> nexus-postgres -> Info -> Internal/External connection string"
echo "   Redis:    Render Dashboard -> nexus-redis -> Info -> Internal connection string"
echo "   These are automatically injected when using render.yaml with fromDatabase/fromService."
echo "   Verify in nexus-api Environment that DATABASE_URL and REDIS_URL exist after first deploy."
echo ""
echo "8) GitHub secrets required for deploy workflow"
echo "   Repository -> Settings -> Secrets and variables -> Actions -> New repository secret"
echo "   Add: RENDER_API_KEY"
echo "   Add: RENDER_NEXUS_API_SERVICE_ID"
echo "   Optional: RENDER_BLUEPRINT_ID"
echo ""

if command -v openssl >/dev/null 2>&1; then
  echo "Suggested secure values"
  echo "  NEXUS_API_KEY=$(openssl rand -hex 32)"
  echo "  JWT_SECRET=$(openssl rand -base64 48 | tr -d '\n')"
  echo "  NEO4J_PASSWORD=$(openssl rand -base64 24 | tr -d '\n')"
  echo "  MINIO_ROOT_USER=nexusminio"
  echo "  MINIO_ROOT_PASSWORD=$(openssl rand -base64 24 | tr -d '\n')"
else
  echo "Install openssl to generate random secrets automatically."
fi
